# Auto-generated by twin-engine blender-scene exporter
# Scene: SCENE_SHOPPABLE_ROOM_IKEA_LIVING_V01
# Stage: ROOM · Profile: REALISTIC
import bpy, math, os

bpy.ops.wm.read_factory_settings(use_empty=True)
sc = bpy.context.scene

sc.render.engine = 'CYCLES'
sc.cycles.samples = 256
sc.cycles.use_denoising = True
sc.render.resolution_x, sc.render.resolution_y = 1600, 1000
sc.render.filepath = '/Users/oskarpeterson/Documents/AI/product twin/repo-platform/data/scenes/shoppable-room-ikea-living/scene-v0.1.png'
sc.render.image_settings.file_format = 'PNG'
sc.view_settings.view_transform = 'AgX'
sc.view_settings.look = 'AgX - Base Contrast'
sc.view_settings.exposure = -0.3

def import_glb(path):
    before = set(bpy.data.objects)
    bpy.ops.import_scene.gltf(filepath=path)
    return [o for o in bpy.data.objects if o not in before]

def place(objs, loc, rot_z_deg):
    for o in objs:
        if o.parent is None:
            o.location = loc
            o.rotation_mode = 'XYZ'
            o.rotation_euler[2] = math.radians(rot_z_deg)

def flat_color(objs, rgb):
    m = bpy.data.materials.new('flat'); m.use_nodes = True
    b = m.node_tree.nodes['Principled BSDF']
    b.inputs['Base Color'].default_value = (*rgb, 1)
    b.inputs['Roughness'].default_value = 0.8
    for o in objs:
        if o.type == 'MESH':
            o.data.materials.clear()
            o.data.materials.append(m)

def mat(name, base, rough, metal=0.0):
    m = bpy.data.materials.new(name); m.use_nodes = True
    b = m.node_tree.nodes['Principled BSDF']
    b.inputs['Base Color'].default_value = (*base, 1)
    b.inputs['Roughness'].default_value = rough
    b.inputs['Metallic'].default_value = metal
    return m

BASE_PATH = '/Users/oskarpeterson/Documents/AI/product twin/repo-platform/data/scenes/shoppable-room-ikea-living'

# Room shell
bpy.ops.mesh.primitive_plane_add(size=12, location=(0, 0, 0))
floor = bpy.context.object
floor.data.materials.append(mat('floor', (0.55, 0.48, 0.38), 0.5))

bpy.ops.mesh.primitive_plane_add(size=12, location=(0, 5, 6))
wall = bpy.context.object
wall.rotation_euler[0] = math.radians(90)
wall.data.materials.append(mat('wall', (0.72, 0.68, 0.62), 0.9))

# Scene elements
# IKEA 3-seat sofa, Tibbleby beige/grey (2280×950×830 mm)
objs_sofa = import_glb(os.path.join(BASE_PATH, 'data/geometry/avatars/ikea-kivik-49440597-g2-sofa-proxy.glb'))
place(objs_sofa, (0.0000, -1.8000, 0.0000), 0)

# IKEA Coffee table, oak veneer (1400×600×370 mm)
objs_coffee_table = import_glb(os.path.join(BASE_PATH, 'data/geometry/avatars/ikea-listerby-30513904-g2-coffee-table-proxy.glb'))
place(objs_coffee_table, (0.0000, -0.2000, 0.0000), 0)

# IKEA Armchair, birch veneer/Knisa light beige (680×820×1000 mm)
objs_armchair = import_glb(os.path.join(BASE_PATH, 'data/geometry/avatars/ikea-poang-39240787-g2-armchair-proxy.glb'))
place(objs_armchair, (2.0000, -1.0000, 0.0000), 30)

# IKEA Tray table, dark grey-green (450×450×530 mm)
objs_side_table = import_glb(os.path.join(BASE_PATH, 'data/geometry/avatars/ikea-gladom-70578451-g2-tray-table-proxy.glb'))
place(objs_side_table, (-1.6000, -1.5000, 0.0000), 0)

# IKEA TV bench, white/Lappviken white (1800×420×380 mm)
objs_tv_bench = import_glb(os.path.join(BASE_PATH, 'data/geometry/avatars/ikea-besta-89330691-g2-media-unit-proxy.glb'))
place(objs_tv_bench, (-2.7000, 0.5000, 0.0000), -90)

# IKEA Bookcase, white (800×280×2020 mm)
objs_bookcase = import_glb(os.path.join(BASE_PATH, 'data/geometry/avatars/ikea-billy-00263850-g2-bookcase-proxy.glb'))
place(objs_bookcase, (2.7000, 0.8000, 0.0000), 90)

# IKEA Rug, flatwoven, natural, 133×195 cm (1330×1950×13 mm)
objs_rug = import_glb(os.path.join(BASE_PATH, 'data/geometry/avatars/ikea-lohals-30511288-g2-rug-proxy.glb'))
place(objs_rug, (0.0000, -0.8000, 0.0050), 0)

# IKEA Floor lamp, ash/white (620×620×1510 mm)
objs_floor_lamp = import_glb(os.path.join(BASE_PATH, 'data/geometry/avatars/ikea-lauters-30405042-g2-floor-lamp-proxy.glb'))
place(objs_floor_lamp, (2.3000, -2.0000, 0.0000), 0)

# Concept Linen cushion, natural (450×450×150 mm)
objs_decor_pillow_a = import_glb(os.path.join(BASE_PATH, 'data/geometry/avatars/concept-cushion-a.glb'))
place(objs_decor_pillow_a, (-0.5700, -1.8000, 0.8300), 0)

# Concept Velvet cushion, sage (400×400×130 mm)
objs_decor_pillow_b = import_glb(os.path.join(BASE_PATH, 'data/geometry/avatars/concept-cushion-b.glb'))
place(objs_decor_pillow_b, (0.0000, -1.8000, 0.8300), 0)

# Concept Wool throw, oatmeal (1300×800×20 mm)
objs_decor_throw = import_glb(os.path.join(BASE_PATH, 'data/geometry/avatars/concept-throw.glb'))
place(objs_decor_throw, (0.0000, -1.8000, 0.8300), 0)

# Concept Ceramic vase, white (140×140×280 mm)
objs_decor_vase = import_glb(os.path.join(BASE_PATH, 'data/geometry/avatars/concept-vase.glb'))
place(objs_decor_vase, (0.0000, -0.2000, 0.3700), 0)

# Environment
w = bpy.data.worlds.new('W'); sc.world = w; w.use_nodes = True
nt = w.node_tree; bg = nt.nodes['Background']
sky = nt.nodes.new('ShaderNodeTexSky')
sky.sun_elevation = math.radians(15)
sky.sun_rotation = math.radians(210)
sky.sun_intensity = 0.3
nt.links.new(sky.outputs['Color'], bg.inputs['Color'])
bg.inputs['Strength'].default_value = 0.5

sun = bpy.data.objects.new('Sun', bpy.data.lights.new('Sun', 'SUN'))
sun.data.energy = 2.8
sun.data.angle = math.radians(1.2)
sun.data.color = (1.0, 0.85, 0.65)
sun.rotation_euler = (math.radians(72), 0, math.radians(35))
sc.collection.objects.link(sun)

# Camera
cam = bpy.data.objects.new('Cam', bpy.data.cameras.new('Cam'))
cam.data.lens = 50
cam.location = (4.5000, 4.5000, 3.2000)
import mathutils
target = mathutils.Vector((0.0000, -0.5000, 0.8000))
direction = target - cam.location
rot_quat = direction.to_track_quat('-Z', 'Y')
cam.rotation_euler = rot_quat.to_euler()
sc.collection.objects.link(cam)
sc.camera = cam

bpy.ops.render.render(write_still=True)
print('WROTE', '/Users/oskarpeterson/Documents/AI/product twin/repo-platform/data/scenes/shoppable-room-ikea-living/scene-v0.1.png')
