/**
 * Blender scene exporter.
 *
 * Takes a parsed twin-scene/v0.1 document and emits a Blender Python script
 * that reconstructs the scene for Cycles rendering. One graph → interactive
 * twin + hero still.
 *
 * Pure module: no DOM, no WebGL. Output is a .py string.
 */

const DEFAULT_RENDER = {
  engine: "CYCLES",
  samples: 256,
  denoising: true,
  resolution: [1600, 1000],
  format: "PNG",
  exposure: -0.3,
  view_transform: "AgX",
  look: "AgX - Base Contrast"
};

const EVIDENCE_COLORS = {
  AUTHORITATIVE: [0.15, 0.45, 0.28],
  INDICATIVE: [0.75, 0.60, 0.25],
  DERIVED: [0.30, 0.50, 0.70],
  REPORTED_UNVERIFIED: [0.60, 0.30, 0.50],
  CONCEPT: [0.50, 0.50, 0.50]
};

function pyVec(arr) {
  return `(${arr.map(v => v.toFixed(4)).join(", ")})`;
}

function pyColor(arr) {
  return `(${arr.map(v => v.toFixed(3)).join(", ")})`;
}

function escPy(s) {
  return s.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

/**
 * @param {object} scene    parsed scene from parseScene()
 * @param {object} [opts]
 * @param {string} [opts.glbBasePath]  prefix for asset_path resolution
 * @param {string} [opts.outputPath]   render output path
 * @param {string} [opts.stage]        stage id for camera (default: first stage)
 * @param {string} [opts.profile]      "INTELLIGENCE" or "REALISTIC" (default: REALISTIC)
 * @param {object} [opts.render]       override DEFAULT_RENDER fields
 * @returns {string} Blender Python script
 */

/**
 * Surface appearance derived from what the catalog row actually says.
 *
 * The G2 proxies ship without manufacturer artwork, so a still of them is bare white unless we
 * give them a surface. We do not invent one per product: the base colour comes from the row's
 * own `color` field and the finish from its `material` field, both mapped through this fixed
 * table. A row that says nothing gets the neutral fabric default, and the scene's existing
 * "textures and finish are representative, not manufacturer artwork" limitation still holds.
 */
const COLOR_WORDS = {
  beige: [0.78, 0.72, 0.61], sand: [0.80, 0.74, 0.62], vit: [0.90, 0.89, 0.86],
  gra: [0.55, 0.55, 0.54], svart: [0.09, 0.09, 0.09], brun: [0.36, 0.26, 0.18],
  blaa: [0.24, 0.33, 0.45], gron: [0.30, 0.38, 0.31], guld: [0.72, 0.58, 0.28],
  antracit: [0.22, 0.23, 0.24], natur: [0.74, 0.66, 0.52]
};
const MATERIAL_WORDS = {
  massing: {rough: 0.32, metal: 0.9, tint: [0.72, 0.55, 0.25]},
  marmor: {rough: 0.16, metal: 0.0, tint: [0.85, 0.84, 0.80]},
  valnot: {rough: 0.45, metal: 0.0, tint: [0.28, 0.17, 0.10]},
  ek: {rough: 0.50, metal: 0.0, tint: [0.55, 0.41, 0.26]},
  furu: {rough: 0.55, metal: 0.0, tint: [0.70, 0.56, 0.36]},
  glas: {rough: 0.06, metal: 0.0, tint: [0.84, 0.88, 0.87]},
  ull: {rough: 0.95, metal: 0.0},
  polyester: {rough: 0.90, metal: 0.0},
  metall: {rough: 0.35, metal: 0.85}
};

const fold = value => String(value ?? "").toLowerCase()
  .replace(/ä/g, "a").replace(/å/g, "aa").replace(/ö/g, "o").replace(/é/g, "e");

export function surfaceFor(element) {
  const commerce = element.commerce ?? {};
  const colorText = fold(commerce.color);
  const materialText = fold(commerce.material);

  let base = null;
  for (const [word, rgb] of Object.entries(COLOR_WORDS)) {
    if (colorText.includes(word)) { base = rgb; break; }
  }
  let finish = null;
  for (const [word, spec] of Object.entries(MATERIAL_WORDS)) {
    if (materialText.includes(word)) { finish = spec; break; }
  }

  const rgb = base ?? finish?.tint ?? [0.76, 0.72, 0.66];
  return {
    rgb: base && finish?.tint && finish.metal > 0.5 ? finish.tint : rgb,
    rough: finish?.rough ?? 0.85,
    metal: finish?.metal ?? 0.0,
    derivedFrom: [commerce.color, commerce.material].filter(Boolean).join(" · ") || "default fabric"
  };
}

export function exportBlenderScene(scene, opts = {}) {
  const windowWattsPerSqm = opts.windowWattsPerSqm ?? 34;
  const {
    glbBasePath = ".",
    outputPath = "./render.png",
    stage: stageId,
    profile = "REALISTIC",
    render: renderOverrides = {},
    // Whole-house scenes carry their own walls, slabs and roof planes. The
    // single-room path below wraps ONE ROOM_VOLUME in a shell, which is exactly
    // wrong for a house with thirteen of them, so structural scenes take a
    // generic path instead: every BOX and GRID_SURFACE is emitted as itself.
    structure = false
  } = opts;

  const render = {...DEFAULT_RENDER, ...renderOverrides};
  const activeStage = stageId
    ? scene.stages.find(s => s.id === stageId) ?? scene.stages[0]
    : scene.stages[0];

  const useIntelligence = profile === "INTELLIGENCE";
  const lines = [];

  function emit(line) { lines.push(line); }

  // Header
  emit("# Auto-generated by twin-engine blender-scene exporter");
  emit(`# Scene: ${escPy(scene.scene_id)}`);
  emit(`# Stage: ${escPy(activeStage.id)} · Profile: ${profile}`);
  emit("import bpy, math, os");
  emit("");

  // Factory reset
  emit("bpy.ops.wm.read_factory_settings(use_empty=True)");
  emit("sc = bpy.context.scene");
  emit("");

  // Render settings
  emit(`sc.render.engine = '${render.engine}'`);
  emit(`sc.cycles.samples = ${opts.samples ?? render.samples}`);
  emit(`sc.cycles.use_denoising = ${render.denoising ? "True" : "False"}`);
  emit(`sc.render.resolution_x, sc.render.resolution_y = ${opts.resolution?.[0] ?? render.resolution[0]}, ${opts.resolution?.[1] ?? render.resolution[1]}`);
  emit(`sc.render.filepath = '${escPy(outputPath)}'`);
  emit(`sc.render.image_settings.file_format = '${render.format}'`);

  // Burn the label into the image itself. A still travels as a file, detached
  // from the scene that made it and from any caption around it, so the claim it
  // is NOT making has to survive the journey: a rendered horizon is never a view
  // claim, and this house is a concept, not a built thing.
  // Kept to one line at the render width: the first version wrapped, and the
  // second line fell outside its background strip onto light pixels, which
  // makes the disclaimer that must survive the journey the least readable
  // thing in the frame. Short label, smaller type, one line.
  const stampLabel = String(scene.subject?.label ?? scene.scene_id).split("—")[0].trim();
  const stamp = [
    "VISUALIZATION",
    escPy(stampLabel),
    "CONCEPT, not a survey",
    "Rendered horizon is not a view claim"
  ].join("  ·  ");
  emit("sc.render.use_stamp = True");
  emit("sc.render.use_stamp_note = True");
  emit("for _f in ('use_stamp_time','use_stamp_date','use_stamp_render_time','use_stamp_frame'," +
       "'use_stamp_scene','use_stamp_camera','use_stamp_filename','use_stamp_lens','use_stamp_marker'):");
  emit("    if hasattr(sc.render, _f): setattr(sc.render, _f, False)");
  emit(`sc.render.stamp_note_text = '${stamp}'`);
  emit("sc.render.stamp_font_size = 16");
  emit("sc.render.use_stamp_labels = False");
  emit("sc.render.stamp_background = (0, 0, 0, 0.72)");
  emit("sc.render.stamp_foreground = (1, 1, 1, 1)");
  emit(`sc.view_settings.view_transform = '${escPy(render.view_transform)}'`);
  emit(`sc.view_settings.look = '${escPy(render.look)}'`);
  emit(`sc.view_settings.exposure = ${render.exposure}`);
  emit("");

  // Helpers
  emit("def import_glb(path):");
  emit("    before = set(bpy.data.objects)");
  emit("    bpy.ops.import_scene.gltf(filepath=path)");
  emit("    return [o for o in bpy.data.objects if o not in before]");
  emit("");
  emit("def place(objs, loc, rot_z_deg):");
  emit("    for o in objs:");
  emit("        if o.parent is None:");
  emit("            o.location = loc");
  emit("            o.rotation_mode = 'XYZ'");
  emit("            o.rotation_euler[2] = math.radians(rot_z_deg)");
  emit("");
  emit("def flat_color(objs, rgb):");
  emit("    m = bpy.data.materials.new('flat'); m.use_nodes = True");
  emit("    b = m.node_tree.nodes['Principled BSDF']");
  emit("    b.inputs['Base Color'].default_value = (*rgb, 1)");
  emit("    b.inputs['Roughness'].default_value = 0.8");
  emit("    for o in objs:");
  emit("        if o.type == 'MESH':");
  emit("            o.data.materials.clear()");
  emit("            o.data.materials.append(m)");
  emit("");
  emit("def tint(objs, rgb, rough, metal, name):");
  emit("    m = bpy.data.materials.new(name); m.use_nodes = True");
  emit("    b = m.node_tree.nodes['Principled BSDF']");
  emit("    b.inputs['Base Color'].default_value = (*rgb, 1)");
  emit("    b.inputs['Roughness'].default_value = rough");
  emit("    b.inputs['Metallic'].default_value = metal");
  emit("    for o in objs:");
  emit("        if o.type == 'MESH':");
  emit("            o.data.materials.clear()");
  emit("            o.data.materials.append(m)");
  emit("");
  emit("def mat(name, base, rough, metal=0.0):");
  emit("    m = bpy.data.materials.new(name); m.use_nodes = True");
  emit("    b = m.node_tree.nodes['Principled BSDF']");
  emit("    b.inputs['Base Color'].default_value = (*base, 1)");
  emit("    b.inputs['Roughness'].default_value = rough");
  emit("    b.inputs['Metallic'].default_value = metal");
  emit("    return m");
  emit("");
  emit(`BASE_PATH = '${escPy(glbBasePath)}'`);
  emit("");

  // Room shell built from the scene's own ROOM_VOLUME — not a stand-in box. The volume carries
  // the real interior size; OPENING elements are cut out of the wall they sit in by building
  // that wall as segments around the hole (a boolean would need the modifier stack to resolve
  // before the camera solve, and segments are exact for a rectangular opening).
  const roomVolume = structure ? null : scene.elements.find(e => e.geometry?.primitive === "ROOM_VOLUME");
  if (roomVolume) {
    const [width, height, depth] = roomVolume.geometry.size;
    const openings = scene.elements.filter(e => e.type === "OPENING" && e.geometry?.primitive === "BOX");
    const T = 0.12;                                  // wall thickness
    emit("# Room shell (from ROOM_VOLUME)");
    emit(`W, H, D, T = ${width}, ${height}, ${depth}, ${T}`);
    emit("def slab(sx, sy, sz, loc, material):");
    emit("    bpy.ops.mesh.primitive_cube_add(size=1, location=loc)");
    emit("    o = bpy.context.object");
    emit("    o.scale = (sx, sy, sz)   # primitive_cube_add(size=1) is already a unit cube");
    emit("    o.data.materials.append(material)");
    emit("    return o");
    emit("");
    emit("m_floor = mat('floor', (0.52, 0.44, 0.34), 0.55)");
    emit("m_wall = mat('wall', (0.74, 0.72, 0.68), 0.92)");
    emit("m_ceil = mat('ceiling', (0.86, 0.85, 0.83), 0.95)");
    emit("slab(W, D, T, (0, 0, -T / 2), m_floor)");
    emit("slab(W, D, T, (0, 0, H + T / 2), m_ceil)");
    // Every wall, and the segments around whatever opening sits in it. An opening rotated 90°
    // lies in an east/west wall and its width runs along z; otherwise it is a north/south wall
    // and the width runs along x. A "fully glazed" wall arrives as one wall-sized opening,
    // which this same segment builder handles — the leftover segments just come out at zero.
    const axisOf = o => (Math.abs(Math.abs(o.geometry.rotation_y_deg ?? 0) - 90) < 1 ? "x" : "z");
    const wallSpecs = [
      {axis: "z", sign: -1, span: width, at: depth / 2},
      {axis: "z", sign: 1, span: width, at: depth / 2},
      {axis: "x", sign: -1, span: depth, at: width / 2},
      {axis: "x", sign: 1, span: depth, at: width / 2}
    ];
    for (const wall of wallSpecs) {
      const offset = (wall.sign * (wall.at + T / 2)).toFixed(3);
      const normalIndex = wall.axis === "z" ? 2 : 0;
      const inWall = openings.filter(o => axisOf(o) === wall.axis
        && Math.sign(o.geometry.position[normalIndex]) === wall.sign
        && Math.abs(Math.abs(o.geometry.position[normalIndex]) - wall.at) < 0.51);

      if (!inWall.length) {
        emit(wall.axis === "z"
          ? `slab(W, T, H, (0, ${offset}, H / 2), m_wall)`
          : `slab(T, D, H, (${offset}, 0, H / 2), m_wall)`);
        continue;
      }
      const seg = (len, centre, tall, base) => {
        if (len <= 0.002 || tall <= 0.002) return;
        emit(wall.axis === "z"
          ? `slab(${len.toFixed(3)}, T, ${tall.toFixed(3)}, (${centre.toFixed(3)}, ${offset}, ${base.toFixed(3)}), m_wall)`
          : `slab(T, ${len.toFixed(3)}, ${tall.toFixed(3)}, (${offset}, ${centre.toFixed(3)}, ${base.toFixed(3)}), m_wall)`);
      };
      for (const opening of inWall) {
        const [ow, oh] = opening.geometry.size;
        const along = opening.geometry.position[wall.axis === "z" ? 0 : 2];
        const cz = opening.geometry.position[1];
        const a0 = along - ow / 2, a1 = along + ow / 2;
        const z0 = cz - oh / 2, z1 = cz + oh / 2;
        const half = wall.span / 2;
        emit(`# opening ${escPy(opening.id)} — ${wall.axis === "z" ? "north/south" : "east/west"} wall built as segments around it`);
        seg(a0 + half, (a0 - half) / 2, height, height / 2);
        seg(half - a1, (a1 + half) / 2, height, height / 2);
        seg(ow, along, z0, z0 / 2);
        seg(ow, along, height - z1, (z1 + height) / 2);
      }
    }
    emit("");
  }

  // Elements
  emit("# Scene elements");
  for (const element of scene.elements) {
    const geom = element.geometry;
    if (geom.primitive !== "GLTF_ASSET") continue;

    const assetPath = geom.asset_path;
    const pos = geom.position ?? [0, 0, 0];
    // three.js: x=east, y=up, z=north → Blender: x=east, y=north, z=up
    const blenderPos = [pos[0], pos[2], pos[1]];
    const rotDeg = -(geom.rotation_y_deg ?? 0);

    emit(`# ${escPy(element.label)}`);
    emit(`objs_${element.id.toLowerCase().replace(/[^a-z0-9]+/g, "_")} = import_glb(os.path.join(BASE_PATH, '${escPy(assetPath)}'))`);
    emit(`place(objs_${element.id.toLowerCase().replace(/[^a-z0-9]+/g, "_")}, ${pyVec(blenderPos)}, ${rotDeg})`);

    const varName = `objs_${element.id.toLowerCase().replace(/[^a-z0-9]+/g, "_")}`;
    if (useIntelligence) {
      const color = EVIDENCE_COLORS[element.evidence_class] ?? EVIDENCE_COLORS.CONCEPT;
      emit(`flat_color(${varName}, ${pyColor(color)})`);
    } else {
      const surface = surfaceFor(element);
      emit(`# surface derived from: ${escPy(surface.derivedFrom)}`);
      emit(`tint(${varName}, ${pyColor(surface.rgb)}, ${surface.rough}, ${surface.metal}, '${escPy(element.id)}')`);
    }
    emit("");
  }

  // Window light. A sealed room lit only by a distant sun renders as a grey box: the opening is
  // a hole, so almost nothing reaches the interior. Each OPENING therefore gets an area light
  // matched to its own size and placed in its own plane, facing in — the daylight that the
  // window in the scene would actually admit, not a studio light invented for the shot.
  if (roomVolume) {
    const openings = scene.elements.filter(e => e.type === "OPENING" && e.geometry?.primitive === "BOX");
    const [width, , depth] = roomVolume.geometry.size;
    for (const opening of openings) {
      const [ow, oh] = opening.geometry.size;
      const onX = Math.abs(Math.abs(opening.geometry.rotation_y_deg ?? 0) - 90) < 1;
      const cz = opening.geometry.position[1];
      const sign = Math.sign(opening.geometry.position[onX ? 0 : 2]) || 1;
      const alongPos = opening.geometry.position[onX ? 2 : 0];
      const inset = sign * ((onX ? width : depth) / 2 - 0.04);
      const cx = onX ? inset : alongPos;
      const y = onX ? alongPos : inset;
      emit(`# Window light from ${escPy(opening.id)} (${ow} × ${oh} m opening)`);
      emit(`wl = bpy.data.lights.new('${escPy(opening.id)}', 'AREA')`);
      emit("wl.shape = 'RECTANGLE'");
      emit(`wl.size, wl.size_y = ${ow}, ${oh}`);
      emit(`wl.energy = ${Math.round(ow * oh * windowWattsPerSqm)}`);
      emit("wl.color = (1.0, 0.96, 0.90)");
      emit(`wo = bpy.data.objects.new('${escPy(opening.id)}_light', wl)`);
      emit(`wo.location = (${typeof cx === "number" ? cx.toFixed(3) : cx}, ${typeof y === "number" ? y.toFixed(3) : y}, ${cz})`);
      emit(`wo.rotation_euler = (math.radians(90), 0, math.radians(${onX ? (sign > 0 ? -90 : 90) : (sign > 0 ? 180 : 0)}))`);
      emit("sc.collection.objects.link(wo)");
      emit("");
    }
  }

  // ── structural geometry (whole-house scenes) ───────────────────────────────
  if (structure) {
    emit("# Structure: every BOX and GRID_SURFACE the scene declares");
    emit("def box(name, loc, size, rot_z_deg, rgb, rough=0.9, metal=0.0, alpha=1.0):");
    emit("    bpy.ops.mesh.primitive_cube_add(size=1, location=loc)");
    emit("    o = bpy.context.object; o.name = name");
    emit("    o.scale = size");
    emit("    o.rotation_mode = 'XYZ'; o.rotation_euler[2] = math.radians(rot_z_deg)");
    emit("    m = bpy.data.materials.new(name); m.use_nodes = True");
    emit("    b = m.node_tree.nodes['Principled BSDF']");
    emit("    b.inputs['Base Color'].default_value = (*rgb, alpha)");
    emit("    b.inputs['Roughness'].default_value = rough");
    emit("    b.inputs['Metallic'].default_value = metal");
    emit("    if alpha < 1.0:");
    emit("        b.inputs['Transmission Weight'].default_value = 0.92");
    emit("        b.inputs['IOR'].default_value = 1.45");
    emit("    o.data.materials.append(m)");
    emit("    return o");
    emit("");
    emit("def quad(name, verts, rgb, rough=0.55, metal=0.25):");
    emit("    mesh = bpy.data.meshes.new(name)");
    emit("    mesh.from_pydata(verts, [], [(0, 1, 3, 2)])");
    emit("    mesh.update()");
    emit("    o = bpy.data.objects.new(name, mesh); bpy.context.collection.objects.link(o)");
    emit("    m = bpy.data.materials.new(name); m.use_nodes = True");
    emit("    b = m.node_tree.nodes['Principled BSDF']");
    emit("    b.inputs['Base Color'].default_value = (*rgb, 1)");
    emit("    b.inputs['Roughness'].default_value = rough");
    emit("    b.inputs['Metallic'].default_value = metal");
    emit("    o.data.materials.append(m)");
    emit("    return o");
    emit("");

    const PALETTE = {
      WALL:       [0.74, 0.71, 0.66],
      FLOOR_SLAB: [0.55, 0.53, 0.50],
      ROOF:       [0.26, 0.27, 0.27],
      TERRAIN:    [0.30, 0.34, 0.24],
      OPENING:    [0.60, 0.74, 0.78]
    };

    for (const el of scene.elements) {
      const g = el.geometry;
      if (!g) continue;
      const rgb = PALETTE[el.type] ?? [0.62, 0.60, 0.57];
      const name = el.id.toLowerCase().replace(/[^a-z0-9]+/g, "_");

      if (g.primitive === "BOX" && g.position && g.size) {
        // three.js [x,y,z] (Y up) -> Blender [x,z,y] (Z up)
        const loc = [g.position[0], g.position[2], g.position[1]];
        const size = [g.size[0], g.size[2], g.size[1]];
        const glass = el.type === "OPENING";
        emit(`box('${escPy(name)}', ${pyVec(loc)}, ${pyVec(size)}, ${-(g.rotation_y_deg ?? 0)}, ${pyColor(rgb)}` +
             `${glass ? ", rough=0.08, metal=0.0, alpha=0.25" : ""})`);
      } else if (g.primitive === "GRID_SURFACE" && Array.isArray(g.vertices)) {
        const verts = g.vertices.map(v => `(${v[0].toFixed(4)}, ${v[2].toFixed(4)}, ${v[1].toFixed(4)})`).join(", ");
        const isGround = el.type === "TERRAIN";
        emit(`quad('${escPy(name)}', [${verts}], ${pyColor(rgb)}` +
             `${isGround ? ", rough=0.95, metal=0.0" : ""})`);
      }
      // ROOM_VOLUME cells are interior reading aids; they would fill the house
      // with translucent boxes in an exterior still, so they are not emitted.
    }
    emit("");
  }

  // Sky and sun
  const solar = scene.document?.studies?.solar;
  emit("# Environment");
  emit("w = bpy.data.worlds.new('W'); sc.world = w; w.use_nodes = True");
  emit("nt = w.node_tree; bg = nt.nodes['Background']");
  emit("sky = nt.nodes.new('ShaderNodeTexSky')");
  emit("sky.sun_elevation = math.radians(15)");
  emit("sky.sun_rotation = math.radians(210)");
  emit("sky.sun_intensity = 0.3");
  emit("nt.links.new(sky.outputs['Color'], bg.inputs['Color'])");
  emit("bg.inputs['Strength'].default_value = 0.55");
  emit("");
  emit("sun = bpy.data.objects.new('Sun', bpy.data.lights.new('Sun', 'SUN'))");
  emit("sun.data.energy = 0.9");
  emit("sun.data.angle = math.radians(1.2)");
  emit("sun.data.color = (1.0, 0.85, 0.65)");
  emit("sun.rotation_euler = (math.radians(72), 0, math.radians(35))");
  emit("sc.collection.objects.link(sun)");
  emit("");

  // Camera. A stage camera authored for the open-stage room sits OUTSIDE the volume (and above
  // the ceiling), which shoots straight through a real wall. When the scene has a ROOM_VOLUME we
  // therefore derive an interior camera instead: standing in a corner at eye height, aimed at the
  // centroid of the furniture actually placed in the room.
  let blenderCam = [activeStage.camera[0], activeStage.camera[2], activeStage.camera[1]];
  let blenderTarget = [activeStage.target[0], activeStage.target[2], activeStage.target[1]];
  let lens = 50;

  if (roomVolume) {
    const [width, , depth] = roomVolume.geometry.size;
    const placed = scene.elements.filter(e => e.geometry?.primitive === "GLTF_ASSET" && e.geometry.position);
    const cx = placed.length ? placed.reduce((s, e) => s + e.geometry.position[0], 0) / placed.length : 0;
    const cz = placed.length ? placed.reduce((s, e) => s + e.geometry.position[2], 0) / placed.length : 0;
    const inset = 0.45;
    const cornerX = (opts.cameraCorner ?? "west") === "east" ? 1 : -1;
    blenderCam = [cornerX * (width / 2 - inset), depth / 2 - inset, 1.42];   // corner, just below standing eye height
    blenderTarget = [cx, cz, 0.58];                              // the seating group, just above seat height
    lens = opts.lens ?? 30;                                      // interior
  }

  emit("# Camera");
  emit("cam = bpy.data.objects.new('Cam', bpy.data.cameras.new('Cam'))");
  emit(`cam.data.lens = ${lens}`);
  emit(`cam.location = ${pyVec(blenderCam)}`);

  // Compute look-at rotation
  emit(`import mathutils`);
  emit(`target = mathutils.Vector(${pyVec(blenderTarget)})`);
  emit(`direction = target - cam.location`);
  emit(`rot_quat = direction.to_track_quat('-Z', 'Y')`);
  emit(`cam.rotation_euler = rot_quat.to_euler()`);
  emit("sc.collection.objects.link(cam)");
  emit("sc.camera = cam");
  emit("");

  // Render
  emit("bpy.ops.render.render(write_still=True)");
  emit(`print('WROTE', '${escPy(outputPath)}')`);

  return lines.join("\n") + "\n";
}
