/**
 * Blender scene exporter.
 *
 * Takes a parsed twin-scene/v0.1 document and emits a Blender Python script
 * that reconstructs the scene for Cycles rendering. One graph → interactive
 * twin + hero still.
 *
 * Pure module: no DOM, no WebGL. Output is a .py string.
 */

const DEFAULT_RENDER = {
  engine: "CYCLES",
  samples: 256,
  denoising: true,
  resolution: [1600, 1000],
  format: "PNG",
  exposure: -0.3,
  view_transform: "AgX",
  look: "AgX - Base Contrast"
};

const EVIDENCE_COLORS = {
  AUTHORITATIVE: [0.15, 0.45, 0.28],
  INDICATIVE: [0.75, 0.60, 0.25],
  DERIVED: [0.30, 0.50, 0.70],
  REPORTED_UNVERIFIED: [0.60, 0.30, 0.50],
  CONCEPT: [0.50, 0.50, 0.50]
};

function pyVec(arr) {
  return `(${arr.map(v => v.toFixed(4)).join(", ")})`;
}

function pyColor(arr) {
  return `(${arr.map(v => v.toFixed(3)).join(", ")})`;
}

function escPy(s) {
  return s.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

/**
 * @param {object} scene    parsed scene from parseScene()
 * @param {object} [opts]
 * @param {string} [opts.glbBasePath]  prefix for asset_path resolution
 * @param {string} [opts.outputPath]   render output path
 * @param {string} [opts.stage]        stage id for camera (default: first stage)
 * @param {string} [opts.profile]      "INTELLIGENCE" or "REALISTIC" (default: REALISTIC)
 * @param {object} [opts.render]       override DEFAULT_RENDER fields
 * @returns {string} Blender Python script
 */
export function exportBlenderScene(scene, opts = {}) {
  const {
    glbBasePath = ".",
    outputPath = "./render.png",
    stage: stageId,
    profile = "REALISTIC",
    render: renderOverrides = {}
  } = opts;

  const render = {...DEFAULT_RENDER, ...renderOverrides};
  const activeStage = stageId
    ? scene.stages.find(s => s.id === stageId) ?? scene.stages[0]
    : scene.stages[0];

  const useIntelligence = profile === "INTELLIGENCE";
  const lines = [];

  function emit(line) { lines.push(line); }

  // Header
  emit("# Auto-generated by twin-engine blender-scene exporter");
  emit(`# Scene: ${escPy(scene.scene_id)}`);
  emit(`# Stage: ${escPy(activeStage.id)} · Profile: ${profile}`);
  emit("import bpy, math, os");
  emit("");

  // Factory reset
  emit("bpy.ops.wm.read_factory_settings(use_empty=True)");
  emit("sc = bpy.context.scene");
  emit("");

  // Render settings
  emit(`sc.render.engine = '${render.engine}'`);
  emit(`sc.cycles.samples = ${render.samples}`);
  emit(`sc.cycles.use_denoising = ${render.denoising ? "True" : "False"}`);
  emit(`sc.render.resolution_x, sc.render.resolution_y = ${render.resolution[0]}, ${render.resolution[1]}`);
  emit(`sc.render.filepath = '${escPy(outputPath)}'`);
  emit(`sc.render.image_settings.file_format = '${render.format}'`);
  emit(`sc.view_settings.view_transform = '${escPy(render.view_transform)}'`);
  emit(`sc.view_settings.look = '${escPy(render.look)}'`);
  emit(`sc.view_settings.exposure = ${render.exposure}`);
  emit("");

  // Helpers
  emit("def import_glb(path):");
  emit("    before = set(bpy.data.objects)");
  emit("    bpy.ops.import_scene.gltf(filepath=path)");
  emit("    return [o for o in bpy.data.objects if o not in before]");
  emit("");
  emit("def place(objs, loc, rot_z_deg):");
  emit("    for o in objs:");
  emit("        if o.parent is None:");
  emit("            o.location = loc");
  emit("            o.rotation_mode = 'XYZ'");
  emit("            o.rotation_euler[2] = math.radians(rot_z_deg)");
  emit("");
  emit("def flat_color(objs, rgb):");
  emit("    m = bpy.data.materials.new('flat'); m.use_nodes = True");
  emit("    b = m.node_tree.nodes['Principled BSDF']");
  emit("    b.inputs['Base Color'].default_value = (*rgb, 1)");
  emit("    b.inputs['Roughness'].default_value = 0.8");
  emit("    for o in objs:");
  emit("        if o.type == 'MESH':");
  emit("            o.data.materials.clear()");
  emit("            o.data.materials.append(m)");
  emit("");
  emit("def mat(name, base, rough, metal=0.0):");
  emit("    m = bpy.data.materials.new(name); m.use_nodes = True");
  emit("    b = m.node_tree.nodes['Principled BSDF']");
  emit("    b.inputs['Base Color'].default_value = (*base, 1)");
  emit("    b.inputs['Roughness'].default_value = rough");
  emit("    b.inputs['Metallic'].default_value = metal");
  emit("    return m");
  emit("");
  emit(`BASE_PATH = '${escPy(glbBasePath)}'`);
  emit("");

  // Room shell: floor + backdrop wall for non-GLTF elements
  const hasRoom = scene.elements.some(e => e.type === "ROOM");
  if (hasRoom) {
    emit("# Room shell");
    emit("bpy.ops.mesh.primitive_plane_add(size=12, location=(0, 0, 0))");
    emit("floor = bpy.context.object");
    emit("floor.data.materials.append(mat('floor', (0.55, 0.48, 0.38), 0.5))");
    emit("");
    emit("bpy.ops.mesh.primitive_plane_add(size=12, location=(0, 5, 6))");
    emit("wall = bpy.context.object");
    emit("wall.rotation_euler[0] = math.radians(90)");
    emit("wall.data.materials.append(mat('wall', (0.72, 0.68, 0.62), 0.9))");
    emit("");
  }

  // Elements
  emit("# Scene elements");
  for (const element of scene.elements) {
    const geom = element.geometry;
    if (geom.primitive !== "GLTF_ASSET") continue;

    const assetPath = geom.asset_path;
    const pos = geom.position ?? [0, 0, 0];
    // three.js: x=east, y=up, z=north → Blender: x=east, y=north, z=up
    const blenderPos = [pos[0], pos[2], pos[1]];
    const rotDeg = -(geom.rotation_y_deg ?? 0);

    emit(`# ${escPy(element.label)}`);
    emit(`objs_${element.id.toLowerCase().replace(/[^a-z0-9]+/g, "_")} = import_glb(os.path.join(BASE_PATH, '${escPy(assetPath)}'))`);
    emit(`place(objs_${element.id.toLowerCase().replace(/[^a-z0-9]+/g, "_")}, ${pyVec(blenderPos)}, ${rotDeg})`);

    if (useIntelligence) {
      const color = EVIDENCE_COLORS[element.evidence_class] ?? EVIDENCE_COLORS.CONCEPT;
      emit(`flat_color(objs_${element.id.toLowerCase().replace(/[^a-z0-9]+/g, "_")}, ${pyColor(color)})`);
    }
    emit("");
  }

  // Sky and sun
  const solar = scene.document?.studies?.solar;
  emit("# Environment");
  emit("w = bpy.data.worlds.new('W'); sc.world = w; w.use_nodes = True");
  emit("nt = w.node_tree; bg = nt.nodes['Background']");
  emit("sky = nt.nodes.new('ShaderNodeTexSky')");
  emit("sky.sun_elevation = math.radians(15)");
  emit("sky.sun_rotation = math.radians(210)");
  emit("sky.sun_intensity = 0.3");
  emit("nt.links.new(sky.outputs['Color'], bg.inputs['Color'])");
  emit("bg.inputs['Strength'].default_value = 0.5");
  emit("");
  emit("sun = bpy.data.objects.new('Sun', bpy.data.lights.new('Sun', 'SUN'))");
  emit("sun.data.energy = 2.8");
  emit("sun.data.angle = math.radians(1.2)");
  emit("sun.data.color = (1.0, 0.85, 0.65)");
  emit("sun.rotation_euler = (math.radians(72), 0, math.radians(35))");
  emit("sc.collection.objects.link(sun)");
  emit("");

  // Camera from stage
  const cam = activeStage.camera;
  const target = activeStage.target;
  const blenderCam = [cam[0], cam[2], cam[1]];

  emit("# Camera");
  emit("cam = bpy.data.objects.new('Cam', bpy.data.cameras.new('Cam'))");
  emit("cam.data.lens = 50");
  emit(`cam.location = ${pyVec(blenderCam)}`);

  // Compute look-at rotation
  emit(`import mathutils`);
  emit(`target = mathutils.Vector(${pyVec([target[0], target[2], target[1]])})`);
  emit(`direction = target - cam.location`);
  emit(`rot_quat = direction.to_track_quat('-Z', 'Y')`);
  emit(`cam.rotation_euler = rot_quat.to_euler()`);
  emit("sc.collection.objects.link(cam)");
  emit("sc.camera = cam");
  emit("");

  // Render
  emit("bpy.ops.render.render(write_still=True)");
  emit(`print('WROTE', '${escPy(outputPath)}')`);

  return lines.join("\n") + "\n";
}
